baseURL = "https://securitiie.github.io"
title = "SecuritIIE"
theme = "gokarna"
languageCode = "fr"
defaultContentLanguage = "fr"
enableEmoji = true
enableRobotsTXT = true
#Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  custom_css = ["static/avatar.css"]
  footer = "SecuritIIE"
  description = "Association de cybersécurité de l'ENSIIE"
  avatarURL = "/images/securitiie.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://linkedin.com/company/securitiie"},
    {name = "email", url = "mailto:securitiie.pro@gmail.com"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[params.meta]
  favicon = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Formations"
    pre = "<span data-feather='book'></span>"
    url = "/formations/"
    weight = 10

  [[menu.main]]
    name = "Guides"
    pre = "<span data-feather='book-open'></span>"
    url = "/guides/"
    weight = 15

  [[menu.main]]
    name = "Infos"
    pre = "<span data-feather='info'></span>"
    url = "/infos/"
    weight = 20

#  [[menu.main]]
#    name = "Tags"
#    pre = "<span data-feather='tag'></span>"
#    url = "/tags/"
#    weight = 40

#  [[menu.main]]
#    identifier = "github"
#    pre = "<span data-feather='github'></span>"
#    url = "https://github.com/526avijitgupta/gokarna"
#    weight = 50

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
